# Generated by Django 6.0.6 on 2026-07-06 15:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from the title if left blank.', max_length=220, unique=True)),
                ('content', models.TextField(help_text='Full post body. Supports Markdown.')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/covers/%Y/%m/')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_published'], name='blog_blog_is_publ_02e44a_idx'), models.Index(fields=['slug'], name='blog_blog_slug_d925e3_idx')],
            },
        ),
    ]
