# Generated by Django 6.0.6 on 2026-07-06 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=150)),
                ('passing_year', models.PositiveIntegerField()),
                ('result', models.CharField(help_text='e.g. CGPA 3.85 / First Class / 90%', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['-passing_year'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if this is a current position.', null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(help_text='Key responsibilities / achievements.')),
            ],
            options={
                'ordering': ['-is_current', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('ai_ml', 'AI/ML'), ('database', 'Database'), ('devops', 'DevOps'), ('other', 'Other')], default='other', max_length=20)),
                ('proficiency_percentage', models.PositiveIntegerField(help_text='1-100', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'ordering': ['category', '-proficiency_percentage'],
            },
        ),
    ]
